-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.accommodation_amenities
(
    accommodation_id integer NOT NULL,
    amenity_id integer NOT NULL,
    CONSTRAINT accommodation_amenities_pkey PRIMARY KEY (accommodation_id, amenity_id)
);

CREATE TABLE IF NOT EXISTS public.accommodations
(
    id serial NOT NULL,
    owner_id integer,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default" NOT NULL,
    city character varying(100) COLLATE pg_catalog."default" NOT NULL,
    country character varying(100) COLLATE pg_catalog."default" NOT NULL,
    postal_code character varying(20) COLLATE pg_catalog."default",
    latitude numeric(9, 6),
    longitude numeric(9, 6),
    star_rating smallint,
    base_currency character varying(10) COLLATE pg_catalog."default" DEFAULT 'ZAR'::character varying,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    is_active boolean DEFAULT true,
    deleted_at timestamp without time zone,
    CONSTRAINT accommodations_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.accommodations
    IS 'Hotel/property listings';

CREATE TABLE IF NOT EXISTS public.admin_audit_logs
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    action character varying(50) COLLATE pg_catalog."default" NOT NULL,
    module character varying(50) COLLATE pg_catalog."default" NOT NULL,
    details jsonb DEFAULT '{}'::jsonb,
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_audit_logs_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.admin_audit_logs
    IS 'Admin action tracking for security';

CREATE TABLE IF NOT EXISTS public.amenities
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    icon character varying(50) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT amenities_pkey PRIMARY KEY (id),
    CONSTRAINT amenities_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.booking_items
(
    id serial NOT NULL,
    booking_id integer NOT NULL,
    room_id integer NOT NULL,
    price_per_night numeric(10, 2) NOT NULL,
    nights integer NOT NULL,
    quantity integer NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT booking_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.bookings
(
    id serial NOT NULL,
    booking_reference character varying(50) COLLATE pg_catalog."default" NOT NULL,
    user_id integer NOT NULL,
    accommodation_id integer NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    total_price numeric(10, 2) NOT NULL,
    currency character varying(10) COLLATE pg_catalog."default" DEFAULT 'ZAR'::character varying,
    check_in_date date NOT NULL,
    check_out_date date NOT NULL,
    guest_count integer NOT NULL DEFAULT 1,
    notes text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    deleted_at timestamp without time zone,
    source character varying(50) COLLATE pg_catalog."default" DEFAULT 'Website'::character varying,
    CONSTRAINT bookings_pkey PRIMARY KEY (id),
    CONSTRAINT bookings_booking_reference_key UNIQUE (booking_reference)
);

COMMENT ON TABLE public.bookings
    IS 'Customer reservations';

COMMENT ON COLUMN public.bookings.source
    IS 'Source of the booking: Website, Mobile App, Phone, Walk-in, etc.';

CREATE TABLE IF NOT EXISTS public.change_audit_logs
(
    id bigserial NOT NULL,
    table_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    record_id bigint NOT NULL,
    user_id integer,
    action character varying(20) COLLATE pg_catalog."default",
    changes jsonb DEFAULT '{}'::jsonb,
    changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT change_audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.currency_rates
(
    id serial NOT NULL,
    base_currency character varying(10) COLLATE pg_catalog."default" NOT NULL,
    target_currency character varying(10) COLLATE pg_catalog."default" NOT NULL,
    rate numeric(12, 6) NOT NULL,
    effective_date date DEFAULT CURRENT_DATE,
    CONSTRAINT currency_rates_pkey PRIMARY KEY (id),
    CONSTRAINT currency_rates_base_currency_target_currency_effective_date_key UNIQUE (base_currency, target_currency, effective_date)
);

CREATE TABLE IF NOT EXISTS public.email_templates
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    subject text COLLATE pg_catalog."default" NOT NULL,
    body text COLLATE pg_catalog."default" NOT NULL,
    variables jsonb DEFAULT '[]'::jsonb,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT email_templates_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.email_templates
    IS 'Email templates for automated communications';

CREATE TABLE IF NOT EXISTS public.favourites
(
    user_id integer NOT NULL,
    accommodation_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT favourites_pkey PRIMARY KEY (user_id, accommodation_id)
);

CREATE TABLE IF NOT EXISTS public.inquiries
(
    id serial NOT NULL,
    guest_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    guest_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    subject character varying(500) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    response text COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'new'::character varying,
    priority character varying(20) COLLATE pg_catalog."default" DEFAULT 'medium'::character varying,
    assigned_to integer,
    responded_by integer,
    responded_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inquiries_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.inquiries
    IS 'Customer support inquiries';

CREATE TABLE IF NOT EXISTS public.login_audit_logs
(
    id serial NOT NULL,
    user_id integer,
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    success boolean,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT login_audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    is_read boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.oauth_providers
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    provider character varying(50) COLLATE pg_catalog."default" NOT NULL,
    provider_user_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT oauth_providers_pkey PRIMARY KEY (id),
    CONSTRAINT oauth_providers_provider_provider_user_id_key UNIQUE (provider, provider_user_id)
);

CREATE TABLE IF NOT EXISTS public.payment_transactions
(
    id serial NOT NULL,
    payment_id integer,
    provider_event jsonb,
    received_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payment_transactions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    id serial NOT NULL,
    booking_id integer,
    user_id integer NOT NULL,
    amount numeric(10, 2) NOT NULL,
    currency character varying(10) COLLATE pg_catalog."default" DEFAULT 'ZAR'::character varying,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    payment_provider character varying(50) COLLATE pg_catalog."default",
    provider_reference character varying(150) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    deleted_at timestamp without time zone,
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.payments
    IS 'Payment transactions';

CREATE TABLE IF NOT EXISTS public.policies
(
    id serial NOT NULL,
    accommodation_id integer NOT NULL,
    policy_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    title character varying(150) COLLATE pg_catalog."default",
    content text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT policies_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.promo_codes
(
    id serial NOT NULL,
    code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    discount_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    discount_value numeric(10, 2) NOT NULL,
    min_purchase_amount numeric(10, 2),
    usage_limit integer,
    usage_count integer DEFAULT 0,
    valid_from date,
    valid_until date,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT promo_codes_pkey PRIMARY KEY (id),
    CONSTRAINT promo_codes_code_key UNIQUE (code)
);

COMMENT ON TABLE public.promo_codes
    IS 'Discount codes for bookings';

CREATE TABLE IF NOT EXISTS public.query_logs
(
    id bigserial NOT NULL,
    query text COLLATE pg_catalog."default",
    duration_ms numeric(10, 3),
    executed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT query_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.refunds
(
    id serial NOT NULL,
    booking_id integer NOT NULL,
    reason text COLLATE pg_catalog."default" NOT NULL,
    refund_amount numeric(10, 2) NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    admin_notes text COLLATE pg_catalog."default",
    transaction_id character varying(100) COLLATE pg_catalog."default",
    requested_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    processed_date timestamp without time zone,
    processed_by integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT refunds_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.refunds
    IS 'Refund requests and processing';

CREATE TABLE IF NOT EXISTS public.reports
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    period character varying(50) COLLATE pg_catalog."default" NOT NULL,
    date_from date,
    date_to date,
    format character varying(20) COLLATE pg_catalog."default" NOT NULL,
    filters jsonb DEFAULT '{}'::jsonb,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    file_path character varying(500) COLLATE pg_catalog."default",
    file_name character varying(255) COLLATE pg_catalog."default",
    file_size bigint,
    error_message text COLLATE pg_catalog."default",
    generated_by integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reports_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.reports
    IS 'Generated reports metadata';

CREATE TABLE IF NOT EXISTS public.reviews
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    accommodation_id integer NOT NULL,
    rating smallint NOT NULL,
    title character varying(150) COLLATE pg_catalog."default",
    comment text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    reviewed_by integer,
    reviewed_at timestamp without time zone,
    rejection_reason text COLLATE pg_catalog."default",
    is_flagged boolean DEFAULT false,
    flag_reason text COLLATE pg_catalog."default",
    flagged_by integer,
    flagged_at timestamp without time zone,
    CONSTRAINT reviews_pkey PRIMARY KEY (id),
    CONSTRAINT reviews_user_id_accommodation_id_key UNIQUE (user_id, accommodation_id)
);

COMMENT ON TABLE public.reviews
    IS 'User reviews and ratings with moderation';

CREATE TABLE IF NOT EXISTS public.room_inventory
(
    id bigserial NOT NULL,
    room_id integer NOT NULL,
    date date NOT NULL,
    available_units integer NOT NULL,
    CONSTRAINT room_inventory_pkey PRIMARY KEY (id),
    CONSTRAINT room_inventory_room_id_date_key UNIQUE (room_id, date)
);

CREATE TABLE IF NOT EXISTS public.room_photos
(
    id serial NOT NULL,
    room_id integer NOT NULL,
    url text COLLATE pg_catalog."default" NOT NULL,
    caption text COLLATE pg_catalog."default",
    sort_order integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT room_photos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.rooms
(
    id serial NOT NULL,
    accommodation_id integer,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    capacity integer NOT NULL DEFAULT 2,
    beds integer DEFAULT 1,
    price_per_night numeric(10, 2) NOT NULL,
    refundable boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    deleted_at timestamp without time zone,
    location character varying(500) COLLATE pg_catalog."default",
    baths integer DEFAULT 2,
    area integer DEFAULT 120,
    type character varying(50) COLLATE pg_catalog."default" DEFAULT 'Standard'::character varying,
    amenities jsonb DEFAULT '[]'::jsonb,
    room_features jsonb DEFAULT '[]'::jsonb,
    quantity integer DEFAULT 10,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'available'::character varying,
    CONSTRAINT rooms_pkey PRIMARY KEY (id),
    CONSTRAINT unique_room_name_per_accommodation UNIQUE (accommodation_id, name)
);

COMMENT ON TABLE public.rooms
    IS 'Room types and pricing';

COMMENT ON COLUMN public.rooms.location
    IS 'Full address/location of the room';

COMMENT ON COLUMN public.rooms.baths
    IS 'Number of bathrooms';

COMMENT ON COLUMN public.rooms.area
    IS 'Area in square meters';

COMMENT ON COLUMN public.rooms.type
    IS 'Room type: Standard, Deluxe, Premium, Suite';

COMMENT ON COLUMN public.rooms.amenities
    IS 'Array of amenity names (e.g., WiFi, Parking)';

COMMENT ON COLUMN public.rooms.room_features
    IS 'Array of room feature descriptions';

COMMENT ON COLUMN public.rooms.quantity
    IS 'Number of units available for this room type';

COMMENT ON COLUMN public.rooms.status
    IS 'Room status: available, unavailable, maintenance';

CREATE TABLE IF NOT EXISTS public.user_tokens
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    token_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    is_used boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT user_tokens_token_key UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    role character varying(20) COLLATE pg_catalog."default" DEFAULT 'user'::character varying,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    is_active boolean DEFAULT true,
    deleted_at timestamp without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

COMMENT ON TABLE public.users
    IS 'User accounts for authentication and profiles';

ALTER TABLE IF EXISTS public.accommodation_amenities
    ADD CONSTRAINT accommodation_amenities_accommodation_id_fkey FOREIGN KEY (accommodation_id)
    REFERENCES public.accommodations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.accommodation_amenities
    ADD CONSTRAINT accommodation_amenities_amenity_id_fkey FOREIGN KEY (amenity_id)
    REFERENCES public.amenities (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.accommodations
    ADD CONSTRAINT accommodations_owner_id_fkey FOREIGN KEY (owner_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.admin_audit_logs
    ADD CONSTRAINT admin_audit_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id
    ON public.admin_audit_logs(user_id);


ALTER TABLE IF EXISTS public.booking_items
    ADD CONSTRAINT booking_items_booking_id_fkey FOREIGN KEY (booking_id)
    REFERENCES public.bookings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.booking_items
    ADD CONSTRAINT booking_items_room_id_fkey FOREIGN KEY (room_id)
    REFERENCES public.rooms (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_accommodation_id_fkey FOREIGN KEY (accommodation_id)
    REFERENCES public.accommodations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_bookings_accommodation
    ON public.bookings(accommodation_id);


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_bookings_user
    ON public.bookings(user_id);


ALTER TABLE IF EXISTS public.change_audit_logs
    ADD CONSTRAINT change_audit_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.favourites
    ADD CONSTRAINT favourites_accommodation_id_fkey FOREIGN KEY (accommodation_id)
    REFERENCES public.accommodations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.favourites
    ADD CONSTRAINT favourites_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.inquiries
    ADD CONSTRAINT inquiries_assigned_to_fkey FOREIGN KEY (assigned_to)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inquiries
    ADD CONSTRAINT inquiries_responded_by_fkey FOREIGN KEY (responded_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.login_audit_logs
    ADD CONSTRAINT login_audit_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.oauth_providers
    ADD CONSTRAINT oauth_providers_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.payment_transactions
    ADD CONSTRAINT payment_transactions_payment_id_fkey FOREIGN KEY (payment_id)
    REFERENCES public.payments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_booking_id_fkey FOREIGN KEY (booking_id)
    REFERENCES public.bookings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_payments_booking
    ON public.payments(booking_id);


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.policies
    ADD CONSTRAINT policies_accommodation_id_fkey FOREIGN KEY (accommodation_id)
    REFERENCES public.accommodations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.refunds
    ADD CONSTRAINT refunds_booking_id_fkey FOREIGN KEY (booking_id)
    REFERENCES public.bookings (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_refunds_booking_id
    ON public.refunds(booking_id);


ALTER TABLE IF EXISTS public.refunds
    ADD CONSTRAINT refunds_processed_by_fkey FOREIGN KEY (processed_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reports
    ADD CONSTRAINT reports_generated_by_fkey FOREIGN KEY (generated_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_reports_generated_by
    ON public.reports(generated_by);


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT reviews_accommodation_id_fkey FOREIGN KEY (accommodation_id)
    REFERENCES public.accommodations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_reviews_accommodation
    ON public.reviews(accommodation_id);


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT reviews_flagged_by_fkey FOREIGN KEY (flagged_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT reviews_reviewed_by_fkey FOREIGN KEY (reviewed_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.room_inventory
    ADD CONSTRAINT room_inventory_room_id_fkey FOREIGN KEY (room_id)
    REFERENCES public.rooms (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.room_photos
    ADD CONSTRAINT room_photos_room_id_fkey FOREIGN KEY (room_id)
    REFERENCES public.rooms (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.rooms
    ADD CONSTRAINT rooms_accommodation_id_fkey FOREIGN KEY (accommodation_id)
    REFERENCES public.accommodations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_rooms_accommodation
    ON public.rooms(accommodation_id);


ALTER TABLE IF EXISTS public.user_tokens
    ADD CONSTRAINT user_tokens_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;